version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    volumes:
      - ./backend:/app
      - backend-go-modules:/go/pkg/mod

  frontend:
    build: 
      context: ./frontend
      target: build
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: bun run dev -- --host 0.0.0.0
    depends_on:
      - backend

volumes:
  backend-go-modules:
