name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Get dependencies
        run: go mod download

      - name: Test
        run: go test ./...

      - name: Build
        run: go build -v ./cmd/server

      - name: Build Docker image
        if: github.event_name == 'release'
        run: |
          docker build -t {{ .ProjectKebab }}-backend:${GITHUB_REF_NAME} .
          docker build -t {{ .ProjectKebab }}-backend:latest .

  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Lint
        run: bun run lint

      - name: Build
        run: bun run build

      - name: Build Docker image
        if: github.event_name == 'release'
        run: |
          docker build -t {{ .ProjectKebab }}-frontend:${GITHUB_REF_NAME} .
          docker build -t {{ .ProjectKebab }}-frontend:latest .
